data <-read.table("household_power_consumption.txt",header=TRUE,sep=";")
data$Date <- strptime(data$Date,"%d/%m/%Y")
newdata <- data[((data$Date == as.POSIXlt("2007-02-01")) | (data$Date == as.POSIXlt("2007-02-02"))),]
newdata$new_time <- paste(newdata$Date,newdata$Time,sep=" ")
newdata$new_time <- strptime(newdata$new_time,"%Y-%m-%d %H:%M:%S")
newdata$Global_active_power <- as.numeric(as.character(newdata$Global_active_power))
newdata$Voltage <- as.numeric(as.character(newdata$Voltage))
newdata$Sub_metering_1 <- as.numeric(as.character(newdata$Sub_metering_1))
newdata$Sub_metering_2 <- as.numeric(as.character(newdata$Sub_metering_2))
newdata$Sub_metering_3 <- as.numeric(as.character(newdata$Sub_metering_3))
newdata$Global_reactive_power <- as.numeric(as.character(newdata$Global_reactive_power))
png(filename="plot4.png",width=480,height=480)
par(mfrow=c(2,2))
with(newdata,plot(newdata$new_time,newdata$Global_active_power,type="l",xlab="",ylab="Global Active Power"))
with(newdata,plot(newdata$new_time,newdata$Voltage,type="l",xlab="datetime",ylab="Voltage"))
with(newdata,plot(newdata$new_time,newdata$Sub_metering_1,type="l",xlab="",ylab="Energy sub metering"))
with(newdata,lines(newdata$new_time,newdata$Sub_metering_2,col="red"))
with(newdata,lines(newdata$new_time,newdata$Sub_metering_3,col="blue"))
legend("topright",col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=c(1,1,1),bty="n")
plot(newdata$new_time,newdata$Global_reactive_power,type="l",xlab="datetime",ylab="Global_reactive_power")
dev.off()